# Generated by Django 5.0.6 on 2024-06-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outflow',
            options={'ordering': ['-created_at'], 'verbose_name': 'Saída', 'verbose_name_plural': 'Saídas'},
        ),
    ]
