# Generated by Django 5.0.6 on 2024-06-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0002_alter_outflow_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
