# Generated by Django 5.0.6 on 2024-06-14 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inflowitem',
            name='unity_cost',
        ),
    ]
