# Generated by Django 5.0.6 on 2024-06-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0002_remove_inflowitem_unity_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inflow',
            options={'ordering': ['-date'], 'verbose_name': 'Entrada', 'verbose_name_plural': 'Entradas'},
        ),
        migrations.AlterField(
            model_name='inflow',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
