# Generated by Django 5.0.6 on 2024-06-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0003_alter_inflow_options_alter_inflow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
